version: '3.8'

services:
  server:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
    container_name: ned-cars_nginx

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: ned-cars_app

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ned-cars
    ports:
      - "9906:3306"
    container_name: ned-cars_db
